
  mesos-dns:
    image: mesosphere/mesos-dns
    command: /mesos-dns -config=/config/mesos-dns.json
    volumes:
      - ./init_scripts/etc/config/:/config/

  master:
    image: mesosphere/mesos-master:1.0.0
    command: /mesos/build/bin/mesos-master.sh
    environment:
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
    ports:
      - 5050:5050

  calico-node:
    net: "container:agent"
    image: calico/node:v0.20.0
    privileged: true
    volumes:
      - /var/lib/modules:/var/lib/modules
    environment:
      - ETCD_AUTHORITY=etcd:2379
      - ETCD_SCHEME=http

  agent:
    image: mesosphere/mesos-slave:1.0.0
    privileged: true
    environment:
      - MESOS_MASTER=master:5050
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_CONTAINERIZERS=mesos
      - MESOS_NETWORK_CNI_PLUGINS_DIR=/cni/bin/
      - MESOS_NETWORK_CNI_CONFIG_DIR=/cni/conf/
      - MESOS_ISOLATION=filesystem/linux,docker/runtime
      - MESOS_IMAGE_PROVIDERS=docker
    volumes:
      - /lib/modules:/lib/modules
      - ./cni/:/cni/
      # - ./images:/tmp/mesos/store/docker/
    links:
      - mesos-dns
      - etcd
      - master
    # dns:
    #   - mesos-dns

  marathon:
    image: djosborne/marathon:unified
    command: --disable_ha
    environment:
      - MARATHON_MASTER=master:5050
      - MARATHON_DISABLE_HA
      - MARATHON_MAX_TASKS_PER_OFFER=32
    ports:
      - 8080:8080
    links:
      - master

  zookeeper:
    image: jplock/zookeeper:3.4.5
    net: "container:marathon"

  etcd:
    image: quay.io/coreos/etcd:v2.3.5
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://localhost:2379
